
# Amazon-Sales-Analysis
#  Data Wrangling
-- Create a database and insert the data using  Table Data Import Wizard.

CREATE DATABASE amazon;
USE amazon;

CREATE TABLE amazon_sales (
    invoice_id VARCHAR(30) NOT NULL,
    branch VARCHAR(5) NOT NULL,
    city VARCHAR(30) NOT NULL,
    customer_type VARCHAR(30) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    product_line VARCHAR(100) NOT NULL,
    unit_price DECIMAL(10 , 2 ) NOT NULL,
    quantity INT NOT NULL,
    VAT FLOAT NOT NULL,
    total DECIMAL(10 , 2 ) NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    cogs DECIMAL(10 , 2 ) NOT NULL,
    gross_margin_percentage FLOAT NOT NULL,
    gross_income DECIMAL(10 , 2 ) NOT NULL,
    rating FLOAT NOT NULL,
    PRIMARY KEY(invoice_id)
);

-- To check the any null values are there or not

select count(*) as null_values_count from amazon_sales
where null;

-- Check the data is inserted or not
SELECT * FROM amazon_sales;
  

# Feature Engineering  

-- adding new columns timeofday, dayname, monthname by extracting values from date and time column --
-- this will help to analyse sales based on month, day of week, time of day --- 


-- Set SQL_Safe_updates = 0 that means we turned off the safe update mode

SET SQL_SAFE_UPDATES= 0;


ALTER TABLE amazon_sales
ADD COLUMN timeofday VARCHAR(50);


UPDATE amazon_sales
SET 
    timeofday = CASE
        WHEN TIME(time) BETWEEN '06:00:00' AND '11:00:00' THEN 'Morning'
        WHEN TIME(time) BETWEEN '12:00:00' AND '17:00:00' THEN 'Afternoon'
        ELSE 'Evening'
    END;
  
    

ALTER TABLE amazon_sales
ADD COLUMN dayname VARCHAR(50);

UPDATE amazon_sales
SET dayname = dayname(date);

ALTER TABLE amazon_sales
ADD COLUMN monthname VARCHAR(20);
 
UPDATE amazon_sales
SET monthname = monthname(date);

-- To check the columns  
select * from amazon_sales limit 5;

# Business Questions To Answer: 
 
# 1.What is the count of distinct cities in the dataset?

select count(distinct city) as Distinct_count_of_cities from amazon_sales;

-- The count of Distinct citites are :  3 -- 

# 2.For each branch, what is the corresponding city?

select distinct branch, city from amazon_sales
order by branch;

-- branches = A, B, C which corresponding cities are A:'Yangon', B:'Mandalay', C:'Naypyitaw'


# 3.What is the count of distinct product lines in the dataset?

select count(distinct product_line) as distinct_count_of_product_line from amazon_sales;

-- The Count of  Distinct Product lines are : 6 --  

# 4.Which payment method occurs most frequently?

select payment_method, count(*) as count from amazon_sales
group by payment_method
order by count desc
limit 1;

-- Ewallet  payment method is most of customers used to paid -- 

# 5.Which product line has the highest sales?

select product_line, sum(quantity) as product_sales from amazon_sales
group by product_line
order by product_sales desc
limit 1;

-- Highest Sales Product Line: Electronic Accessories (Units Sold:971) --
-- Lowest Sales Product Line: Health and Beauty (Unit Sold: 854) --


# 6.How much revenue is generated each month?

select monthname, sum(total) as total_revenue from amazon_sales
group by monthname
order by total_revenue desc;

-- Highest Revenue generated by 'January':'116292.11' -- 
-- Month With Lowest Revenue: February : 97219.58 --


# 7.In which month did the cost of goods sold reach its peak?

select monthname, sum(cogs) as cogs_sold from amazon_sales
group by monthname
order by cogs_sold desc
limit 1;

-- In Month Of January cogs reach its peak  : 110754.16 -- 

# 8.Which product line generated the highest revenue?

select product_line, sum(total) as total_revenue from amazon_sales
group by product_line
order by total_revenue desc
limit 1;

-- Highest Revenue Product Line: Food and Beverages ($ 56144.96)--
-- Lowest Revenue Product Line: Health and Beauty ($ 49193.84) --

# 9.In which city was the highest revenue recorded?

select branch,city, sum(total) as total_revenue from amazon_sales
group by city,branch
order by total_revenue desc
;

-- City with highest revenue 'Naypyitaw': 110568.86 and branch is 'C' -- 
-- City with lowest revenue is 'Mandalay' : 106198.00 and branch is 'B' -- 

# 10.Which product line incurred the highest Value Added Tax?

select product_line, max(VAT) as highest_Vat from amazon_sales
group by product_line
order by highest_Vat desc
limit 1;

-- highest VAT paying productline is 'Fashion accessories' : 49.65 --

# 11.For each product line, add a column indicating "Good" if its sales are above average, otherwise "Bad."

select product_line, sum(total) as total_revenue,
case
when sum(total) > (select sum(total)/ count(distinct product_line) from amazon_sales) then 'Good'
else 'Bad'
end as sales_performance
from amazon_sales
group by product_line
order by total_revenue desc;

-- Check the Sales performance if total sales is greter than average sales then perforamace is 'Good' else 'Bad --

# 12.Identify the branch that exceeded the average number of products sold. 

select branch, sum(quantity) as product_sold from amazon_sales
group by branch
having product_sold > (select sum(quantity)/ count(distinct branch) as avg_products_sold from amazon_sales);

-- branch 'A' is sold the products greater than the average products --  


# 13.Which product line is most frequently associated with each gender?

with productline_with_gender as (
select product_line, gender , count(*) as count from amazon_sales
group by product_line,gender),
max_count as  
(select max(count) from productline_with_gender
group by gender)

select * from productline_with_gender
where count in (select * from max_count)
order by count desc
limit 2;

--  Here 'Fashion accessories' product line is mostly associated with 'Female' --
-- and 'Health and beauty' product line is mostly associated with 'Male' -- 


# 14.Calculate the average rating for each product line. 

select product_line, avg(rating) as avg_rating from amazon_sales
group by product_line
order by avg_rating desc;

-- It calculate the average ratings of each product line --

# 15.Count the sales occurrences for each time of day on every weekday.

select timeofday,dayname,count(*) as total_sales from amazon_sales
group by timeofday,dayname
order by 
case dayname
    when 'Sunday' then 1
    when 'Monday' then 2
    when 'Tuesday' then 3
    when 'Wednesday' then 4
    when 'Thursday' then 5
    when 'Friday' then 6
    when 'Saturday' then 7
    else 'None'
END
 , 
case timeofday
when 'Morning' then 1
when 'Afternoon' then 2
when 'Evening' then 3
end;

-- It count how many sales are occurred in a day and which time of  day sales will occurs -- 

# 16.Identify the customer type contributing the highest revenue.

select customer_type, sum(total) as total_revenue from amazon_sales
group by customer_type
order by total_revenue desc
limit 1;

-- Highest Revenue Customer Type: Member  - 164223.81 --

# 17.Determine the city with the highest VAT percentage. 

select city, ((sum(VAT)/ sum(total)) * 100) as vat_percentage from amazon_sales
group by city
order by vat_percentage desc
limit 1;

-- Highest VAT percentage city is  Naypyitaw : 4.761898133409432 --

# 18.Identify the customer type with the highest VAT payments

select customer_type, sum(VAT) as total_vat from amazon_sales
group by customer_type
order by total_vat desc
limit 1;

-- Highest VAT payments customer_type is Member: 7820.163996100426 --


# 19.What is the count of distinct customer types in the dataset? 

select count(distinct customer_type) as distinct_count_of_customertype from amazon_sales;

-- The Count of Distinct Customer_type is : 2 --

# 20.What is the count of distinct payment methods in the dataset? 

select count(distinct payment_method) as distinct_count_of_payment_methods 
from amazon_sales;

-- Count of Distinct Payment Methods : 3 -- 

# 21.Which customer type occurs most frequently?

select customer_type,count(*) as customer_type_count from amazon_sales
group by customer_type
order by customer_type_count desc
limit 1;

-- The most frequently occurs customer_type is : Member-501

# 22.Identify the customer type with the highest purchase frequency.

select customer_type, sum(total) as purchase_frequency from amazon_sales
group by customer_type
order by purchase_frequency desc
limit 1;

-- Highest purchase frequency customer_type is : Member : 164223.81

# 23.Determine the predominant gender among customers.

select gender,count(*) as gender_count from amazon_sales
group by gender
order by gender_count desc;

-- predominant gender among customers : Female - 501 --

# 24.Examine the distribution of genders within each branch.

select branch, gender, count(*) as gender_count from amazon_sales
group by branch,gender
order by branch,gender;

--  How many Male and Feamles are in each branch --

# 25.Identify the time of day when customers provide the most ratings.

select timeofday, count(rating) as ratings_count from amazon_sales
group by timeofday
order by ratings_count desc
limit 1;

--  Customers Provide most ratings in :time of day - 'Afternoon' --

# 26.Determine the time of day with the highest customer ratings for each branch.

-- branch, timeofday, highest_ratings

select branch,timeofday, 
max(rating) as highest_ratings
from amazon_sales
group by branch, timeofday
having max(rating) = (select max(rating) from amazon_sales)
order by branch; 

-- Which time of day , customers provide highest rating in each branch --

# 27.Identify the day of the week with the highest average ratings.

select dayname, avg(rating) as avg_rating from amazon_sales
group by dayname
order by avg_rating desc
limit 1;

--  "Monday" would be the day with the highest average rating and '7.153599990844727' would be the average rating on that day --  

# 28.Determine the day of the week with the highest average ratings for each branch.

-- branch, dayname, highest_avg_ratings

with average_rating as (
select branch,dayname,  avg(rating) as avg_rating from amazon_sales
group by branch,dayname),
max_rating as 
(select max(avg_rating) from average_rating 
group by branch)

select branch,dayname,avg_rating as highest_avg_ratings from average_rating
where avg_rating in (select * from max_rating);

-- Day with Highest average ratings for each branch -- 
